export const transactions = [
  {
    id: 1,
    date: "2025-09-16",
    description: "ONLINE TRANSFER TO CHEKINGS $25.00",
    type: "credit",
    transac: "Deposit",
    amount: 25,
  },
];

export const savingTransactions = [
  {
    id: 1,
    date: "2024-11-12",
    type: "credit",
    description: "SAVINGS TRANSFER IN",
    transac: "Transfer",
    amount: 50000,
  },
  {
    id: 2,
    date: "2024-12-01",
    type: "credit",
    description: "INTEREST PAYMENT",
    transac: "Interest",
    amount: 1250,
  },
  {
    id: 3,
    date: "2024-12-20",
    type: "debit",
    description: "TRANSFER TO CHECKING",
    transac: "Transfer",
    amount: 11500,
  },
  {
    id: 4,
    date: "2025-01-05",
    type: "credit",
    description: "DEPOSIT - PAYROLL ADJ",
    transac: "Deposit",
    amount: 200000,
  },
  {
    id: 5,
    date: "2025-02-11",
    type: "debit",
    description: "ACH PAYMENT - INVESTMENT",
    transac: "ACH",
    amount: 120000,
  },
  {
    id: 6,
    date: "2025-03-08",
    type: "credit",
    description: "TRANSFER FROM BROKER",
    transac: "Transfer",
    amount: 48500,
  },
  {
    id: 7,
    date: "2025-03-22",
    type: "credit",
    description: "SAVINGS - DIRECT DEPOSIT",
    transac: "Direct Deposit",
    amount: 25000,
  },
  {
    id: 8,
    date: "2025-04-14",
    type: "debit",
    description: "TRANSFER TO MONEY MARKET",
    transac: "Transfer",
    amount: 235000,
  },
  {
    id: 9,
    date: "2025-05-09",
    type: "credit",
    description: "GIFT/TRANSFER RECEIVED",
    transac: "Deposit",
    amount: 700000,
  },
  {
    id: 10,
    date: "2025-05-28",
    type: "debit",
    description: "TRANSFER TO CITIBANK CHECKING",
    transac: "Transfer",
    amount: 240000,
  },
  {
    id: 11,
    date: "2025-06-10",
    type: "credit",
    description: "INTEREST ADJUSTMENT",
    transac: "Interest",
    amount: 480,
  },
  {
    id: 12,
    date: "2025-06-30",
    type: "debit",
    description: "CHECK 1023 (SAVINGS)",
    transac: "Check",
    amount: 35625,
  },
  {
    id: 13,
    date: "2025-07-19",
    type: "credit",
    description: "INVESTMENT REDEMPTION",
    transac: "ACH",
    amount: 600000,
  },
  {
    id: 14,
    date: "2025-08-05",
    type: "debit",
    description: "ACCT ADJUSTMENT - TRANSFER OUT",
    transac: "Bank Adjustment",
    amount: 108500,
  },
  {
    id: 15,
    date: "2025-08-29",
    type: "credit",
    description: "PAYMENT FROM EMPLOYER (SAV)",
    transac: "Direct Deposit",
    amount: 1250,
  },
  {
    id: 16,
    date: "2025-09-10",
    type: "debit",
    description: "SAVINGS FEE (SIMULATED)",
    transac: "Fee",
    amount: 182825,
  },
  {
    id: 17,
    date: "2025-09-18",
    type: "credit",
    description: "TRANSFER FROM CHECKING",
    transac: "Transfer",
    amount: 3000,
  },
  {
    id: 18,
    date: "2025-10-02",
    type: "credit",
    description: "YEARLY BONUS DEPOSIT",
    transac: "Deposit",
    amount: 200000,
  },
  {
    id: 19,
    date: "2025-10-22",
    type: "debit",
    description: "TRANSFER TO ESCROW",
    transac: "Transfer",
    amount: 100000,
  },
  {
    id: 20,
    date: "2025-11-01",
    type: "credit",
    description: "ADJUSTMENT - SIMULATED",
    transac: "Bank Adjustment",
    amount: 48500,
  },
  {
    id: 21,
    date: "2025-11-05",
    type: "credit",
    description: "SAVINGS INTEREST PAYMENT",
    transac: "Interest",
    amount: 1500,
  },
  {
    id: 22,
    date: "2025-11-07",
    type: "debit",
    description: "TRANSFER TO CHECKING (PAY)",
    transac: "Transfer",
    amount: 1500,
  },
  {
    id: 23,
    date: "2025-11-09",
    type: "credit",
    description: "FINAL ADJUSTMENT - SIMULATED",
    transac: "Bank Adjustment",
    amount: 50000,
  },
  {
    id: 24,
    date: "2025-11-09",
    type: "credit",
    description: "SIMULATED BALANCE ADJUST",
    transac: "Bank Adjustment",
    amount: 1000000,
  },
];

// Selected Date
export const timeOptions = [
  { id: 5, label: "Last 7 Days", value: "7" },
  { id: 1, label: "Last 30 Days", value: "30" },
  { id: 2, label: "Last 3 Months", value: "90" },
  { id: 3, label: "Last 6 Months", value: "180" },
  { id: 4, label: "Last 12 Months", value: "365" },
];

// Selected By Debit Or Credit
export const typeOptions = [
  { id: 1, label: "Show All", value: "all" },
  { id: 2, label: "Debits", value: "debit" },
  { id: 3, label: "Credits", value: "credit" },
];

import { PiFileTextLight } from "react-icons/pi";
import { SlPrinter } from "react-icons/sl";

// Records of Statement
export const statement = [
  { id: 1, label: "View Last Statement", value: PiFileTextLight },
  { id: 2, label: "Print", value: SlPrinter },
];
