export const transactions = [
  {
    id: 1,
    date: "2024-09-05",
    type: "credit",
    description: "WIRE CREDIT FROM AUTO DEALER SALE",
    transac: "Wire",
    amount: 1150000,
  },
  {
    id: 2,
    date: "2024-09-10",
    type: "debit",
    description: "ACH DEBIT PAYROLL EXPENSES",
    transac: "Transfer",
    amount: 228000,
  },
  {
    id: 3,
    date: "2024-09-15",
    type: "debit",
    description: "POS PURCHASE HOME DEPOT",
    transac: "POS",
    amount: 33200,
  },
  {
    id: 4,
    date: "2024-09-20",
    type: "credit",
    description: "MOBILE DEPOSIT CLIENT CHECK",
    transac: "Check",
    amount: 445000,
  },
  {
    id: 5,
    date: "2024-09-25",
    type: "debit",
    description: "WIRE TRANSFER TO SUPPLIER GERMANY",
    transac: "Wire",
    amount: 1525000,
  },
  {
    id: 6,
    date: "2024-10-02",
    type: "credit",
    description: "ONLINE TRANSFER FROM BUSINESS PARTNER",
    transac: "Transfer",
    amount: 860000,
  },
  {
    id: 7,
    date: "2024-10-05",
    type: "debit",
    description: "POS PURCHASE UNITED AIRLINES",
    transac: "POS",
    amount: 27200,
  },
  {
    id: 8,
    date: "2024-10-12",
    type: "debit",
    description: "ZELLE PAYMENT CONTRACTOR",
    transac: "Zelle",
    amount: 68500,
  },
  {
    id: 9,
    date: "2024-10-20",
    type: "credit",
    description: "WIRE CREDIT AUTO EXPORT SALE",
    transac: "Wire",
    amount: 290000,
  },
  {
    id: 10,
    date: "2024-10-28",
    type: "debit",
    description: "ACH DEBIT OFFICE RENT",
    transac: "Transfer",
    amount: 102000,
  },
  {
    id: 11,
    date: "2024-11-03",
    type: "credit",
    description: "MOBILE DEPOSIT CLIENT CHECK",
    transac: "Check",
    amount: 610000,
  },
  {
    id: 12,
    date: "2024-11-10",
    type: "debit",
    description: "POS PURCHASE SHELL OIL",
    transac: "POS",
    amount: 12200,
  },
  {
    id: 13,
    date: "2024-11-14",
    type: "debit",
    description: "WIRE TRANSFER TO SUPPLIER JAPAN",
    transac: "Wire",
    amount: 1375000,
  },
  {
    id: 14,
    date: "2024-11-22",
    type: "credit",
    description: "ONLINE TRANSFER CLIENT PAYMENT",
    transac: "Transfer",
    amount: 945000,
  },
  {
    id: 15,
    date: "2024-12-01",
    type: "debit",
    description: "ZELLE PAYMENT CONSULTANT",
    transac: "Zelle",
    amount: 55400,
  },
  {
    id: 16,
    date: "2024-12-07",
    type: "credit",
    description: "WIRE CREDIT AUTO SALE",
    transac: "Wire",
    amount: 360000,
  },
  {
    id: 17,
    date: "2024-12-14",
    type: "debit",
    description: "POS PURCHASE MARRIOTT HOTEL",
    transac: "POS",
    amount: 47200,
  },
  {
    id: 18,
    date: "2024-12-20",
    type: "debit",
    description: "ACH DEBIT PAYROLL EXPENSES",
    transac: "Transfer",
    amount: 381500,
  },
  {
    id: 19,
    date: "2025-01-04",
    type: "credit",
    description: "MOBILE DEPOSIT CLIENT CHECK",
    transac: "Check",
    amount: 792000,
  },
  {
    id: 20,
    date: "2025-01-10",
    type: "debit",
    description: "WIRE TRANSFER TO SUPPLIER ITALY",
    transac: "Wire",
    amount: 201000,
  },
  {
    id: 21,
    date: "2025-01-17",
    type: "credit",
    description: "WIRE CREDIT AUTO DEALER SALE",
    transac: "Wire",
    amount: 1180000,
  },
  {
    id: 22,
    date: "2025-01-25",
    type: "debit",
    description: "POS PURCHASE TESLA SUPERCHARGER",
    transac: "POS",
    amount: 750,
  },
  {
    id: 23,
    date: "2025-02-01",
    type: "credit",
    description: "ONLINE TRANSFER CLIENT PAYMENT",
    transac: "Transfer",
    amount: 125000,
  },
  {
    id: 24,
    date: "2025-02-08",
    type: "debit",
    description: "ZELLE PAYMENT EMPLOYEE BONUS",
    transac: "Zelle",
    amount: 10500,
  },
  {
    id: 25,
    date: "2025-02-14",
    type: "debit",
    description: "ACH DEBIT OFFICE RENT",
    transac: "Transfer",
    amount: 12000,
  },
  {
    id: 26,
    date: "2025-02-20",
    type: "credit",
    description: "WIRE CREDIT FROM AUTO EXPORT",
    transac: "Wire",
    amount: 220000,
  },
  {
    id: 27,
    date: "2025-03-03",
    type: "debit",
    description: "POS PURCHASE AMAZON BUSINESS",
    transac: "POS",
    amount: 5400,
  },
  {
    id: 28,
    date: "2025-03-10",
    type: "credit",
    description: "MOBILE DEPOSIT CLIENT CHECK",
    transac: "Check",
    amount: 86000,
  },
  {
    id: 29,
    date: "2025-03-15",
    type: "debit",
    description: "WIRE TRANSFER TO SUPPLIER KOREA",
    transac: "Wire",
    amount: 190000,
  },
  {
    id: 30,
    date: "2025-04-01",
    type: "credit",
    description: "WIRE CREDIT AUTO SALES REVENUE",
    transac: "Wire",
    amount: 275000,
  },
  {
    id: 31,
    date: "2025-04-12",
    type: "debit",
    description: "POS PURCHASE AMERICAN AIRLINES",
    transac: "POS",
    amount: 3100,
  },
  {
    id: 32,
    date: "2025-05-06",
    type: "debit",
    description: "ACH DEBIT PAYROLL EXPENSES",
    transac: "Transfer",
    amount: 33000,
  },
  {
    id: 33,
    date: "2025-06-01",
    type: "credit",
    description: "ONLINE TRANSFER CLIENT PAYMENT",
    transac: "Transfer",
    amount: 110000,
  },
  {
    id: 34,
    date: "2025-07-18",
    type: "debit",
    description: "WIRE TRANSFER TO SUPPLIER USA",
    transac: "Wire",
    amount: 145000,
  },
  {
    id: 35,
    date: "2025-08-15",
    type: "credit",
    description: "WIRE CREDIT AUTO DEALER SALE",
    transac: "Wire",
    amount: 250000,
  },
];

export const savingTransactions = [
  {
    id: 1,
    date: "2024-09-08",
    type: "credit",
    description: "ONLINE TRANSFER FROM CHECKING",
    transac: "Transfer",
    amount: 50000,
  },
  {
    id: 2,
    date: "2024-09-20",
    type: "credit",
    description: "WIRE CREDIT BUSINESS PROFITS",
    transac: "Wire",
    amount: 75000,
  },
  {
    id: 3,
    date: "2024-09-25",
    type: "debit",
    description: "WIRE TRANSFER TO INVESTMENT FUND",
    transac: "Wire",
    amount: 40000,
  },
  {
    id: 4,
    date: "2024-10-02",
    type: "credit",
    description: "ONLINE TRANSFER FROM CHECKING",
    transac: "Transfer",
    amount: 60000,
  },
  {
    id: 5,
    date: "2024-10-18",
    type: "debit",
    description: "WIRE TRANSFER TO BROKERAGE ACCOUNT",
    transac: "Wire",
    amount: 30000,
  },
  {
    id: 6,
    date: "2024-11-05",
    type: "credit",
    description: "ONLINE TRANSFER FROM CHECKING",
    transac: "Transfer",
    amount: 85000,
  },
  {
    id: 7,
    date: "2024-11-12",
    type: "debit",
    description: "WIRE TRANSFER TO INVESTMENT FUND",
    transac: "Wire",
    amount: 55000,
  },
  {
    id: 8,
    date: "2024-11-22",
    type: "credit",
    description: "WIRE CREDIT AUTO EXPORT PROFITS",
    transac: "Wire",
    amount: 98910,
  },
  {
    id: 9,
    date: "2024-12-04",
    type: "credit",
    description: "ONLINE TRANSFER FROM CHECKING",
    transac: "Transfer",
    amount: 490000,
  },
  {
    id: 10,
    date: "2024-12-16",
    type: "debit",
    description: "WIRE TRANSFER TO BROKERAGE ACCOUNT",
    transac: "Wire",
    amount: 215000,
  },
  {
    id: 11,
    date: "2025-01-07",
    type: "credit",
    description: "ONLINE TRANSFER FROM CHECKING",
    transac: "Transfer",
    amount: 70000,
  },
  {
    id: 12,
    date: "2025-01-15",
    type: "debit",
    description: "WIRE TRANSFER TO REAL ESTATE FUND",
    transac: "Wire",
    amount: 60000,
  },
  {
    id: 13,
    date: "2025-01-30",
    type: "credit",
    description: "WIRE CREDIT AUTO EXPORT PROFITS",
    transac: "Wire",
    amount: 85000,
  },
  {
    id: 14,
    date: "2025-02-10",
    type: "credit",
    description: "ONLINE TRANSFER FROM CHECKING",
    transac: "Transfer",
    amount: 95000,
  },
  {
    id: 15,
    date: "2025-02-22",
    type: "debit",
    description: "WIRE TRANSFER TO INVESTMENT FUND",
    transac: "Wire",
    amount: 40000,
  },
  {
    id: 16,
    date: "2025-03-06",
    type: "credit",
    description: "WIRE CREDIT AUTO EXPORT PROFITS",
    transac: "Wire",
    amount: 105000,
  },
  {
    id: 17,
    date: "2025-03-18",
    type: "debit",
    description: "WIRE TRANSFER TO BROKERAGE ACCOUNT",
    transac: "Wire",
    amount: 30000,
  },
  {
    id: 18,
    date: "2025-04-02",
    type: "credit",
    description: "ONLINE TRANSFER FROM CHECKING",
    transac: "Transfer",
    amount: 60000,
  },
  {
    id: 19,
    date: "2025-04-10",
    type: "debit",
    description: "WIRE TRANSFER TO INVESTMENT FUND",
    transac: "Wire",
    amount: 45000,
  },
  {
    id: 20,
    date: "2025-04-22",
    type: "credit",
    description: "WIRE CREDIT AUTO SALES PROFITS",
    transac: "Wire",
    amount: 80000,
  },
  {
    id: 21,
    date: "2025-05-03",
    type: "credit",
    description: "ONLINE TRANSFER FROM CHECKING",
    transac: "Transfer",
    amount: 70000,
  },
  {
    id: 22,
    date: "2025-05-16",
    type: "debit",
    description: "WIRE TRANSFER TO INVESTMENT FUND",
    transac: "Wire",
    amount: 35000,
  },
  {
    id: 23,
    date: "2025-06-01",
    type: "credit",
    description: "WIRE CREDIT BUSINESS PROFITS",
    transac: "Wire",
    amount: 65000,
  },
  {
    id: 24,
    date: "2025-06-12",
    type: "credit",
    description: "ONLINE TRANSFER FROM CHECKING",
    transac: "Transfer",
    amount: 55000,
  },
  {
    id: 25,
    date: "2025-06-20",
    type: "debit",
    description: "WIRE TRANSFER TO BROKERAGE ACCOUNT",
    transac: "Wire",
    amount: 40000,
  },
  {
    id: 26,
    date: "2025-07-04",
    type: "credit",
    description: "ONLINE TRANSFER FROM CHECKING",
    transac: "Transfer",
    amount: 60000,
  },
  {
    id: 27,
    date: "2025-07-15",
    type: "debit",
    description: "WIRE TRANSFER TO REAL ESTATE FUND",
    transac: "Wire",
    amount: 50000,
  },
  {
    id: 28,
    date: "2025-07-24",
    type: "credit",
    description: "WIRE CREDIT AUTO EXPORT PROFITS",
    transac: "Wire",
    amount: 75000,
  },
  {
    id: 29,
    date: "2025-08-03",
    type: "credit",
    description: "ONLINE TRANSFER FROM CHECKING",
    transac: "Transfer",
    amount: 85000,
  },
  {
    id: 30,
    date: "2025-08-10",
    type: "debit",
    description: "WIRE TRANSFER TO INVESTMENT FUND",
    transac: "Wire",
    amount: 55000,
  },
  {
    id: 31,
    date: "2025-08-15",
    type: "credit",
    description: "WIRE CREDIT AUTO SALES PROFITS",
    transac: "Wire",
    amount: 90000,
  },
  {
    id: 32,
    date: "2025-08-18",
    type: "credit",
    description: "ONLINE TRANSFER FROM CHECKING",
    transac: "Transfer",
    amount: 70000,
  },
  {
    id: 33,
    date: "2025-08-20",
    type: "debit",
    description: "WIRE TRANSFER TO BROKERAGE ACCOUNT",
    transac: "Wire",
    amount: 45000,
  },
  {
    id: 34,
    date: "2025-08-23",
    type: "credit",
    description: "ONLINE TRANSFER FROM CHECKING",
    transac: "Transfer",
    amount: 60000,
  },
  {
    id: 35,
    date: "2025-08-25",
    type: "debit",
    description: "WIRE TRANSFER TO INVESTMENT FUND",
    transac: "Wire",
    amount: 30000,
  },
];

// Selected Date
export const timeOptions = [
  { id: 5, label: "Last 7 Days", value: "7" },
  { id: 1, label: "Last 30 Days", value: "30" },
  { id: 2, label: "Last 3 Months", value: "90" },
  { id: 3, label: "Last 6 Months", value: "180" },
  { id: 4, label: "Last 12 Months", value: "365" },
];

// Selected By Debit Or Credit
export const typeOptions = [
  { id: 1, label: "Show All", value: "all" },
  { id: 2, label: "Debits", value: "debit" },
  { id: 3, label: "Credits", value: "credit" },
];

import { PiFileTextLight } from "react-icons/pi";
import { SlPrinter } from "react-icons/sl";

// Records of Statement
export const statement = [
  { id: 1, label: "View Last Statement", value: PiFileTextLight },
  { id: 2, label: "Print", value: SlPrinter },
];
