export const transactions = [
  {
    id: 1,
    date: "2024-10-12",
    type: "credit",
    description: "DIRECT DEP - PAYROLL (STUDIO)",
    transac: "Direct Deposit",
    amount: 51238,
  },
  {
    id: 2,
    date: "2024-10-20",
    type: "debit",
    description: "POS PURCHASE - THEATER BOX OFFICE",
    transac: "Debit Card",
    amount: 1220,
  },
  {
    id: 3,
    date: "2024-11-05",
    type: "debit",
    description: "ACH PMT - RENT (APT 4B)",
    transac: "ACH",
    amount: 23500,
  },
  {
    id: 4,
    date: "2024-11-18",
    type: "credit",
    description: "CHECK DEPOSIT - PERSONAL CHECK #205",
    transac: "Check",
    amount: 3000,
  },
  {
    id: 5,
    date: "2024-12-02",
    type: "debit",
    description: "ONLINE TRANSFER TO SAVINGS - AUTO SWEEP",
    transac: "Transfer",
    amount: 5000,
  },
  {
    id: 6,
    date: "2024-12-07",
    type: "debit",
    description: "POS PURCHASE - CLOTHING BOUTIQUE",
    transac: "Debit Card",
    amount: 450,
  },
  {
    id: 7,
    date: "2024-12-22",
    type: "credit",
    description: "DIRECT DEP - PERFORMANCE BONUS",
    transac: "Direct Deposit",
    amount: 2500,
  },
  {
    id: 8,
    date: "2025-01-03",
    type: "debit",
    description: "ATM WITHDRAWAL - CASH",
    transac: "ATM",
    amount: 200,
  },
  {
    id: 9,
    date: "2025-01-15",
    type: "debit",
    description: "ACH PMT - GYM MEMBERSHIP",
    transac: "ACH",
    amount: 75,
  },
  {
    id: 10,
    date: "2025-02-01",
    type: "credit",
    description: "TRANSFER FROM SAVINGS (MOVIE ADVANCE)",
    transac: "Transfer",
    amount: 10000,
  },
  {
    id: 11,
    date: "2025-02-14",
    type: "debit",
    description: "POS PURCHASE - DINING",
    transac: "Debit Card",
    amount: 120,
  },
  {
    id: 12,
    date: "2025-03-02",
    type: "debit",
    description: "ACH PMT - AGENT FEE",
    transac: "ACH",
    amount: 1500,
  },
  {
    id: 13,
    date: "2025-03-20",
    type: "credit",
    description: "DIRECT DEP - CONTRACT (TV EPISODE)",
    transac: "Direct Deposit",
    amount: 15000,
  },
  {
    id: 14,
    date: "2025-04-05",
    type: "debit",
    description: "ONLINE TRANSFER TO SAVINGS - INVESTMENT",
    transac: "Transfer",
    amount: 20000,
  },
  {
    id: 15,
    date: "2025-04-17",
    type: "debit",
    description: "POS PURCHASE - FLIGHT (INTL)",
    transac: "Debit Card",
    amount: 800,
  },
  {
    id: 16,
    date: "2025-05-01",
    type: "debit",
    description: "CHECK #223 - RENT REBATE",
    transac: "Check",
    amount: 250,
  },
  {
    id: 17,
    date: "2025-05-10",
    type: "credit",
    description: "DIRECT DEP - PAYROLL (STUDIO)",
    transac: "Direct Deposit",
    amount: 3000,
  },
  {
    id: 18,
    date: "2025-05-22",
    type: "debit",
    description: "POS PURCHASE - EQUIPMENT RENTAL",
    transac: "Debit Card",
    amount: 400,
  },
  {
    id: 19,
    date: "2025-06-09",
    type: "debit",
    description: "ONLINE TRANSFER TO SAVINGS - TAX RESERVE",
    transac: "Transfer",
    amount: 2500,
  },
  {
    id: 20,
    date: "2025-06-21",
    type: "debit",
    description: "ACH PMT - CHARITY DONATION",
    transac: "ACH",
    amount: 300,
  },
  {
    id: 21,
    date: "2025-07-04",
    type: "credit",
    description: "DIRECT DEP - ROYALTY PAYMENT",
    transac: "Direct Deposit",
    amount: 800,
  },
  {
    id: 22,
    date: "2025-07-18",
    type: "debit",
    description: "POS PURCHASE - GROCERY",
    transac: "Debit Card",
    amount: 160,
  },
  {
    id: 23,
    date: "2025-08-01",
    type: "credit",
    description: "TRANSFER FROM SAVINGS - CASHFLOW",
    transac: "Transfer",
    amount: 2000,
  },
  {
    id: 24,
    date: "2025-08-12",
    type: "debit",
    description: "POS PURCHASE - PHOTOGRAPHY STUDIO",
    transac: "Debit Card",
    amount: 600,
  },
  {
    id: 25,
    date: "2025-08-27",
    type: "debit",
    description: "ACH PMT - PROPERTY TAX",
    transac: "ACH",
    amount: 1500,
  },
  {
    id: 26,
    date: "2025-09-10",
    type: "credit",
    description: "DIRECT DEP - SPECIAL APPEARANCE",
    transac: "Direct Deposit",
    amount: 2000,
  },
  {
    id: 27,
    date: "2025-09-25",
    type: "debit",
    description: "CARD PURCHASE - CLOTHING",
    transac: "Debit Card",
    amount: 325,
  },
  {
    id: 28,
    date: "2025-10-02",
    type: "debit",
    description: "ONLINE TRANSFER TO SAVINGS - INVESTMENT",
    transac: "Transfer",
    amount: 6000,
  },
  {
    id: 29,
    date: "2025-10-08",
    type: "credit",
    description: "DIRECT DEP - FINAL SETTLEMENT",
    transac: "Direct Deposit",
    amount: 10000,
  },
];

export const savingTransactions = [
  {
    id: 1,
    date: "2024-10-15",
    type: "credit",
    description: "TRANSFER FROM CHECKING - AUTO SWEEP",
    transac: "Transfer",
    amount: 51000,
  },
  {
    id: 2,
    date: "2024-10-28",
    type: "credit",
    description: "INTEREST CREDIT",
    transac: "Interest",
    amount: 425,
  },
  {
    id: 3,
    date: "2024-11-05",
    type: "debit",
    description: "ONLINE TRANSFER TO INVESTMENT ACCT",
    transac: "Transfer",
    amount: 23000,
  },
  {
    id: 4,
    date: "2024-11-30",
    type: "credit",
    description: "ACH CREDIT - INVESTMENT PROCEEDS",
    transac: "ACH",
    amount: 14000,
  },
  {
    id: 5,
    date: "2024-12-01",
    type: "credit",
    description: "AUTOMATIC SAVINGS DEPOSIT",
    transac: "Transfer",
    amount: 15500,
  },
  {
    id: 6,
    date: "2024-12-05",
    type: "credit",
    description: "INTL WIRE IN - FILM RIGHTS",
    transac: "Wire",
    amount: 36000,
  },
  {
    id: 7,
    date: "2024-12-12",
    type: "debit",
    description: "TRANSFER TO CHECKING - MOVIE ADVANCE",
    transac: "Transfer",
    amount: 17000,
  },
  {
    id: 8,
    date: "2025-01-10",
    type: "credit",
    description: "ACH CREDIT - YEAR-END REFUND",
    transac: "ACH",
    amount: 18200,
  },
  {
    id: 9,
    date: "2025-01-28",
    type: "credit",
    description: "ACH CREDIT - ROI (INVESTMENT)",
    transac: "ACH",
    amount: 5000,
  },
  {
    id: 10,
    date: "2025-02-01",
    type: "debit",
    description: "WIRE OUT - AGENT SETTLEMENT",
    transac: "Wire",
    amount: 4000,
  },
  {
    id: 11,
    date: "2025-02-14",
    type: "credit",
    description: "TRANSFER FROM CHECKING - BONUS ALLOCATION",
    transac: "Transfer",
    amount: 2500,
  },
  {
    id: 12,
    date: "2025-02-25",
    type: "debit",
    description: "ONLINE TRANSFER TO BROKERAGE",
    transac: "Transfer",
    amount: 7000,
  },
  {
    id: 13,
    date: "2025-03-01",
    type: "credit",
    description: "INTEREST CREDIT",
    transac: "Interest",
    amount: 52,
  },
  {
    id: 14,
    date: "2025-03-15",
    type: "credit",
    description: "TRANSFER FROM CHECKING - TAX RESERVE",
    transac: "Transfer",
    amount: 2500,
  },
  {
    id: 15,
    date: "2025-03-20",
    type: "debit",
    description: "ACH PMT - PROPERTY MANAGEMENT",
    transac: "ACH",
    amount: 1200,
  },
  {
    id: 16,
    date: "2025-04-07",
    type: "credit",
    description: "ACH CREDIT - ROYALTIES",
    transac: "ACH",
    amount: 7000,
  },
  {
    id: 17,
    date: "2025-04-18",
    type: "debit",
    description: "TRANSFER TO CHECKING - CASHFLOW",
    transac: "Transfer",
    amount: 2000,
  },
  {
    id: 18,
    date: "2025-04-30",
    type: "credit",
    description: "INTL WIRE IN - DISTRIBUTION",
    transac: "Wire",
    amount: 15000,
  },
  {
    id: 19,
    date: "2025-05-12",
    type: "debit",
    description: "ACH PMT - MORTGAGE (AUTOPAY)",
    transac: "ACH",
    amount: 2500,
  },
  {
    id: 20,
    date: "2025-05-30",
    type: "credit",
    description: "ESTATE DISTRIBUTION (ACH)",
    transac: "ACH",
    amount: 8000,
  },
  {
    id: 21,
    date: "2025-06-05",
    type: "debit",
    description: "TRANSFER TO CHECKING - VACATION FUND",
    transac: "Transfer",
    amount: 3000,
  },
  {
    id: 22,
    date: "2025-06-18",
    type: "debit",
    description: "ACH PMT - CHARITABLE GIFT",
    transac: "ACH",
    amount: 1500,
  },
  {
    id: 23,
    date: "2025-06-25",
    type: "credit",
    description: "ACH CREDIT - INVESTMENT RETURN",
    transac: "ACH",
    amount: 6000,
  },
  {
    id: 24,
    date: "2025-07-04",
    type: "credit",
    description: "AUTOMATIC SAVINGS DEPOSIT",
    transac: "Transfer",
    amount: 1000,
  },
  {
    id: 25,
    date: "2025-07-22",
    type: "credit",
    description: "ACH CREDIT - INVESTMENT SALE",
    transac: "ACH",
    amount: 20000,
  },
  {
    id: 26,
    date: "2025-08-05",
    type: "debit",
    description: "TRANSFER TO CHECKING - SHORTFALL",
    transac: "Transfer",
    amount: 2000,
  },
  {
    id: 27,
    date: "2025-08-29",
    type: "credit",
    description: "INTEREST CREDIT",
    transac: "Interest",
    amount: 60,
  },
  {
    id: 28,
    date: "2025-09-10",
    type: "credit",
    description: "ACH CREDIT - ENDORSEMENT FEE",
    transac: "ACH",
    amount: 3000,
  },
  {
    id: 29,
    date: "2025-09-20",
    type: "debit",
    description: "WIRE OUT - PROPERTY PURCHASE (DEPOSIT)",
    transac: "Wire",
    amount: 12000,
  },
  {
    id: 30,
    date: "2025-10-08",
    type: "debit",
    description: "ADJUSTMENT - INTERNAL TRANSFER TO REACH TARGET",
    transac: "Transfer",
    amount: 22000,
  },
];

// Selected Date
export const timeOptions = [
  { id: 5, label: "Last 7 Days", value: "7" },
  { id: 1, label: "Last 30 Days", value: "30" },
  { id: 2, label: "Last 3 Months", value: "90" },
  { id: 3, label: "Last 6 Months", value: "180" },
  { id: 4, label: "Last 12 Months", value: "365" },
];

// Selected By Debit Or Credit
export const typeOptions = [
  { id: 1, label: "Show All", value: "all" },
  { id: 2, label: "Debits", value: "debit" },
  { id: 3, label: "Credits", value: "credit" },
];

import { PiFileTextLight } from "react-icons/pi";
import { SlPrinter } from "react-icons/sl";

// Records of Statement
export const statement = [
  { id: 1, label: "View Last Statement", value: PiFileTextLight },
  { id: 2, label: "Print", value: SlPrinter },
];
